- hosts: webserver
  tasks:
  - name: Execute a command on the host
    command: hostname -s
    register: hostname_output
  - name: show  the hostname_output
    debug:
     var: hostname_output
  - name: Show Ipaddress of the host servers
    debug:
     msg="The ipaddress of host server  is {{ansible_default_ipv4.address}}"
  - name: print variable
    debug:
     var=ansible_default_ipv4.address
  - name: Execute a command on the host
    command: hostname -s
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "8") or
          (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "20")
    register: hostname_output
  - name: show  the hostname_output
    debug:
     var: hostname_output.stdout     
